version: "3"

services:
####################### API Backend Definition #######################
  dotnet-webapi:
    container_name: issuer-api-backend
    build:
      context: issuer-api/
      dockerfile: openshift.dockerfile
    networks:
      - openshift
####################### Networks Definition #######################
networks:
  openshift:

