name: dev-api

on:
  push:
    branches:
      - develop

jobs:
  build-backend:
    runs-on: ubuntu-latest
    environment: Development
    env:
      SERVICE_NAME: issuer-api-dev
      CONTAINER_NAME: moh-vvc-issuer-api
      IMAGE_TAG: dev

    steps:
      - name: "Checkout the repo"
        uses: actions/checkout@v2

      - name: "Login to OpenShift repository"
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_TOOLS_SERVICE_ACCOUNT_USERNAME}}
          password: ${{secrets.OPENSHIFT_TOOLS_SERVICE_ACCOUNT_PASSWORD}}

      - name: "Build, tag and push .NET web API image"
        id: build-image
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker-compose -f oc4-compose.yml build --force-rm --no-cache \
            --build-arg ASPNETCORE_HTTPS_PORT=5001 \
            --build-arg ASPNETCORE_ENVIRONMENT="Development" \
            --build-arg ASPNETCORE_URLS="http://+:8080" \
            --build-arg DOTNET_CLI_HOME="/tmp/DOTNET_CLI_HOME" \
            $SERVICE_NAME
          docker tag moh-vvc-issuer_$SERVICE_NAME ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/$CONTAINER_NAME:$IMAGE_TAG
          docker image push ${{secrets.OPENSHIFT_IMAGE_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/$CONTAINER_NAME:$IMAGE_TAG

  apply-oc-template:
    runs-on: ubuntu-20.04
    environment: Development
    steps:
      - name: "Use the OpenShift template"
        uses: actions/checkout@v2

      - name: Install OC
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: "4.6"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL}}
          openshift_token: ${{secrets.OPENSHIFT_SERVICE_TOKEN}}
          namespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-dev

      - name: "Process template"
        id: oc
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          IMAGE_TAG: dev
          SVC_NAME: vvc
        run: |
          oc process -f openshift/vvc-issuer.yml \
            -p SVC_NAME=$SVC_NAME \
            -p IMAGE_TAG=$IMAGE_TAG \
            -p OC_NAMESPACE=${{secrets.OPENSHIFT_LICENSE_PLATE}} \
            -p OC_APP=dev \
            -p URL_STUB=-${{secrets.OPENSHIFT_LICENSE_PLATE}}-dev.apps.silver.devops.gov.bc.ca \
            -n ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{secrets.OC_APP}} | oc apply -n ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{secrets.OC_APP}} -f -
